version: "3"

services:
  web:
   container_name: nodeapp
   restart: always
   build: .
   ports:
     - "1818:3000"
   links:
     - mongo
   volumes:
     - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: "none"
